Automatically create missing release store directories
This is especially useful if another team member adds an additional
release store to a shared butido configuration.

Butido used to fail if a release store is missing (e.g., when running "butido build"):
```
[00:00:00] (100%): ████████████████████████████████████████ | Loaded releases in /srv/butido/releases/a successfully
Error: build command failed

Caused by:
    StoreRoot path does not point to directory: /srv/butido/releases/b
```

Now, it'll simply try to create the missing directory transparently:
```
[00:00:00] (100%): ████████████████████████████████████████ | Loaded releases in /srv/butido/releases/a successfully
2023-03-24T19:52:33.864478Z  INFO butido::filestore::path: Creating the missing release store directory /srv/butido/releases/b
[00:00:00] (100%): ████████████████████████████████████████ | Loaded releases in /srv/butido/releases/b successfully
```

Fixes #192.

Signed-off-by: Michael Weiss <michael.weiss@atos.net>