clap: Fix all custom value parsers
This fixes a regression from f2567d0 that causes panics/crashes.

A `clap::builder::ValueParser` doesn't only parse/validate argument
values but also determines the final type of the argument and handles
the conversion. From the documentation [0]:
> `ValueParser` defines how to convert a raw argument value into a
> validated and typed value for use within an application.

A custom `TypedValueParser` [1] can be implemented via
`Fn(&str) -> Result<T, E>`. In this case, the type `T` represents the
type of the argument after parsing (as used by the application).

Our custom value parsers used the "unit" type `()` for the result.
This caused panics at runtime due to type mismatches that couldn't be
detected during compile time. An example from a debug build:
```
$ butido build -E DEBUG=1 -I local:default tree 1.8.0
[00:00:16] (100%): ████████████████████████████████████████ | Repository loading finished
2023-03-13T20:14:21.881237Z  INFO butido::commands::build: Endpoint config build
2023-03-13T20:14:21.881503Z  INFO butido::commands::build: We want tree (Some(PackageVersion("1.8.0")))
thread 'main' panicked at 'Mismatch between definition and access of `env`. Could not downcast to alloc::string::String, need to downcast to ()
', src/commands/build.rs:141:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It would be best to use the desired types instead of `String`s to avoid
code-duplication but I decided to only fix the regression for now and
improve the typing in a dedicated PR as that requires additional changes
and further improvements can be made (more typing, the parse_{usize,u64}
functions aren't required anymore, etc.).

[0]: https://docs.rs/clap/latest/clap/builder/struct.ValueParser.html
[1]: https://docs.rs/clap/latest/clap/builder/trait.TypedValueParser.html

Signed-off-by: Michael Weiss <michael.weiss@atos.net>