Show which package file caused the loading of the repository to fail
The error message didn't state which file caused the error:
```
$ butido source download hello
Error: Loading the repository

Caused by:
    missing field `name`
```

This makes it very difficult to find and fix the issue in the packages
repository.

Now, the error message contains the location of the leaf package TOML
file that caused the error:
```
$ butido source download hello
Error: Loading the repository

Caused by:
    0: Could not load package configuration: tree/1.42/pkg.toml
    1: missing field `name`
```

Fix #47

Signed-off-by: Michael Weiss <michael.weiss@atos.net>
Co-authored-by: Nico Steinle <nico.steinle@atos.net>
Tested-by: Michael Weiss <michael.weiss@atos.net>