Provide context when adding an edge to the package dependency DAG fails
This can happen when the package repository contains cyclic
dependencies. The DAG library would only emit `WouldCycle` as error
message, which isn't enough to trace down the cycle. This adds enough
context to find the final DAG edge that would complete the cycle, e.g.:
```
$ butido build -I deb12 tree 1.8.0
[...]
Error: build command failed

Caused by:
    0: Failed to add package dependency DAG edge from package "tree" (1.8.0) to dependency "vim" (9.0.2153)
    1: WouldCycle
```

This resolves #52.

Signed-off-by: Michael Weiss <michael.weiss@eviden.com>