Revert "Update dependency: clap: 3.0.0-beta.2 -> ^3.0.0"
This reverts commit 399348c4a7b960c91bd5a4af8dff0bc778c1a050.

clap changed from 3.0.0-beta.2 to 3.0.0,
with 3.0.0 we get this error:

$ butido build tmux -I local:rh8-default 3.3a
error: Found argument '3.3a' which wasn't expected, or isn't valid in this context
USAGE:
    butido2 build [OPTIONS] --image <IMAGE NAME> <NAME> [--] [VERSION]

so for now we stick wieth 3.0.0-beta.2