Force you to run butido from the top-level git path
Running it from subdirectories gives out misleading error messages.
For example:
```
$ butido source download git =2.39.3
Error: Loading the repository

Caused by:
    0: Reading file from filesystem: bash/5.0/pkg.toml
    1: No such file or directory (os error 2)
```

Fixes #170

Signed-off-by: Nico Steinle <nico.steinle@atos.net>