Fix the parsing of `env` CLI arguments
Setting ArgSettings::MultipleValues requires setting
ArgSettings::TakesValue [0]. This fixes the following issue:
```
$ butido build tree -I local:default -E DEBUG=1 -L -- 1.8.0
error: Found argument '1.8.0' which wasn't expected, or isn't valid in this context

USAGE:
    butido build [OPTIONS] --image <IMAGE NAME> <NAME> [--] [VERSION]

For more information try --help
```

All other arguments with multiple=true already have takes_value=true set.
In the case of the `env` argument, this only became an issue since the clap
update from 3.0.0-beta.2 to 3.2.23.

[0]: https://docs.rs/clap/3.2.23/clap/builder/struct.Arg.html#method.multiple_values

Signed-off-by: Michael Weiss <michael.weiss@atos.net>